name: test
on:
  schedule:
    # UTC timezone -> TW timezone '0 23 * * 3,4'
    - cron: '10 15 * * 0,1,2'  # Only on even week number
    - cron: '10 15 * * 3,4'  # On every week
    - cron: '10 15 * * 5,6'  # Only on odd week number
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: morristseng/get-current-time@900acdf959618039454d6c56db2106be16b7804d
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - name: Use current time odd
        if: ${{ (github.event.schedule == '10 15 * * 3,4') || (github.event.schedule == '10 15 * * 5,6' && steps.current-time.outputs.isOddWeek) || (github.event.schedule == '10 15 * * 0,1,2' && !steps.current-time.outputs.isOddWeek)}}
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
