steps:
  - name: Get current time
    uses: morristseng/get-current-time@900acdf959618039454d6c56db2106be16b7804d
    id: current-time
    with:
      format: YYYYMMDD-HH
      utcOffset: "+08:00"
  - name: Use current time odd
    if: ${{ strps.current-time.outputs.isOddWeek }}
    env:
      TIME: "${{ steps.current-time.outputs.time }}"
      R_TIME: "${{ steps.current-time.outputs.readableTime }}"
      F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
      YEAR: "${{ steps.current-time.outputs.year }}"
      DAY: "${{ steps.current-time.outputs.day }}"
    run: echo odd $TIME $R_TIME $F_TIME $YEAR $DAY
  - name: Use current time even
    if: ${{ !strps.current-time.outputs.isOddWeek }}
    env:
      TIME: "${{ steps.current-time.outputs.time }}"
      R_TIME: "${{ steps.current-time.outputs.readableTime }}"
      F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
      YEAR: "${{ steps.current-time.outputs.year }}"
      DAY: "${{ steps.current-time.outputs.day }}"
    run: echo even $TIME $R_TIME $F_TIME $YEAR $DAY
